---
title: "EPID 600 Project Template"
author: "Your Name"
output: html_document
---

Use this template to complete your project throughout the course. Your Final Project presentation in class will be based on the contents of this document. Due dates:

- Topic choice: 9/18/15
- List of faculty/staff to be contacted: 10/2/15
- Complete overview with data source to address a specific problem identified: 10/16/15
- Introduction: 10/30/15
- Methods and Results draft: 11/13/15
- Final Document: 11/30/15

### Overview
In this section, give a brief a description of your project and its goal, what data you are using to complete it, and what three faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. 


### Introduction 
In the first paragraph, describe the problem addressed, its significance, and some background to motivate the problem.

In the second paragraph, explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.

Title: Predicting Warfarin Dosage from clinical and pharmacogenetic data

The formation of blood clots in the blood vessels and their migration else where in the body can be prevented by warfarin, an anticoagulant.More than 30 million patients are prescribed warfarin, however, the proper dose of warfarin is difficult to determine because it can vary amongnpatients by a factor of 10. The consequences of taking the incorrect dose can be fatal. The first dose administered is usually 5 mg and the time it takes for the blood to clot is measured. This is called Prothrombin Time(PT) or the International Normalized Ratio(INR). INR is the same as PT but normalized based on a person of the same demographic. The INR value should be prolonged by the warfarin, and based on this measure, the next daily dose will be adjusted. The patient has to stay in the hospital until the INR value is in the normal range for at least 2 repetitions. Studies have shown that warfarin activity can be determined partially by genetic factors. Specifically, the two variants in VKORC1 and CYP2C9, which are genes involved in warfarin response. 

The goal of this project is to predict therapeutic warfarin dosage by applying machine learning approaches to a large publicly avaiable data that integrates clincal information as well as genotypic data. The data consists of 5,700 patients and 67 features and by utilizing computational and statistical methods to successfully predict warfarin dosage, the cost and time of adminstration of warfarin dosage will reduce significantly. 

This project is highly interdisciplinary, as it combined the field of pharmacology, genomics, computer science, statistics, and health care. Integrating knowledge from these disciplines will contribute to the field of precision medicine and will change how health care is practiced by improving the prognosis, diagnosis, and treatment of patients.

### Methods
In the first paragraph, describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.


The International Warfarin Pharmacogenomic Consortium comprised of 21 research groups that have contributed clinical and genetic data for 5,700 subjects who were treated with warfarin. Clinical factors that have been previously associated with warfarin therapy and easily accessible were chosen. The data consists of features regarding demographic information, primary indication of warfarin treatment, the stable therapeutic dose of warfarin, the INR achieved with a stable warfarin dose, the desired INR, the use of concomitant medications, the presence of variants of CYP2C9 AND VKORC1. There is also information regarding race, whether or not the patient is a current smoker, and intake of herbal medication, vitamins, and supplement. However, the missing-ness rate was very large, so it was removed. The outcome variable was the stable therapeutic dose of warfarin, defined as the steady-state dose that led to stable anticoagulation levels.

The data was tested for missinginess rate for features and individuals, in order to see if any variable or subject should be thrown out for lack of succificent data. The initial total of 63 variables were reduced to 23 variables, and individuals that did not have data for all of the 23 variables were thrown out to work on a completed dataset. Linear regression was performed individuall for each feature, to determine if there are any features that are significantly associated with therapeutic dosage. These variables will be then chosen for a model to train through cross-validation. Different methods/models are currently being explored.

Code used to clean and explore data is currently in project_warfarin.R.

### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address.

By performing linear regression on each variable, the following features were shown to be signficantly associated with therapeutic dosage of warfarin: Site, Race defined by Office of Management and Budget, Combined separate genotypes for *2 and *3 into single CYP2C9 diplotypes with possible values *1/*1, *1/*2, *1/*3, *2/*2, *2/*3, *3/*3, VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231; C/T, weight, whether or not they had a valve replacement, whether or not they take aspirin, whether or not they take Simvastatin, VKORC1 QC genotype: -1639 G>A (3673); chr16:31015190; rs9923231; C/T, INR reported, and whether or not they reached stable dose. 


